import type { GlossaryCategory } from './index'

export const multipartGlossary: GlossaryCategory[] = [
  {
    category: 'Multipart Uploads',
    terms: [
      {
        term: 'multipart/form-data',
        definition:
          'An HTTP content type that bundles multiple data parts (text fields and binary files) into a single request body, separated by boundary strings. Defined in RFC 2046.',
        linkId: 'rfc-2046',
        sectionId: 'multipart-uploads-guide',
      },
      {
        term: 'FormData',
        definition:
          'A browser API for constructing key-value pairs representing form fields and files. When passed as a fetch body, the browser automatically sets the correct multipart Content-Type header with boundary.',
        linkId: 'mdn-formdata',
        sectionId: 'multipart-uploads-guide',
      },
      {
        term: 'Boundary String',
        definition:
          'A unique delimiter generated by the browser that separates each part in a multipart request body. Included in the Content-Type header so the server knows where each part begins and ends.',
        linkId: 'rfc-2046',
        sectionId: 'multipart-uploads-guide',
      },
      {
        term: 'Resumable Upload',
        definition:
          'An upload protocol (such as tus) that can resume from the last successfully received byte after a connection drop, avoiding re-uploading the entire file from scratch.',
        linkId: 'tus-protocol',
        sectionId: 'multipart-uploads-guide',
      },
      {
        term: 'Presigned URL',
        definition:
          'A time-limited URL generated by a server that authorizes a client to upload directly to cloud storage (S3, GCS, R2), bypassing the application server for the actual file transfer.',
        linkId: 'mdn-fetch',
        sectionId: 'multipart-uploads-guide',
      },
    ],
  },
]
